cd ../tasks
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gpt4 gpt4
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gemma gemma
python3 run_cheat_task.py ../reproductions/Autosave-China-60 llama3 llama3
python3 run_cheat_task.py ../reproductions/Autosave-China-60 mistral mistral
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gpt3.5 gpt3.5
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gpt4 mistral
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gpt4 gemma
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gpt4 llama3
python3 run_cheat_task.py ../reproductions/Autosave-China-60 mistral gemma
python3 run_cheat_task.py ../reproductions/Autosave-China-60 mistral llama3
python3 run_cheat_task.py ../reproductions/Autosave-China-60 mistral gpt4
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gemma llama3
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gemma gpt4
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gemma mistral
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gpt3.5 gpt4
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gpt3.5 mistral
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gpt3.5 gemma
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gpt3.5 llama3
python3 run_cheat_task.py ../reproductions/Autosave-China-60 llama3 gpt3.5
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gpt4 gpt3.5
python3 run_cheat_task.py ../reproductions/Autosave-China-60 mistral gpt3.5
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gemma gpt3.5
python3 run_cheat_task.py ../reproductions/Autosave-China-60 llama3 mistral
python3 run_cheat_task.py ../reproductions/Autosave-China-60 llama3 gemma
python3 run_cheat_task.py ../reproductions/Autosave-China-60 llama3 gpt4
python3 run_cheat_task.py ../reproductions/Autosave-China-60 mistral llama3
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gemma mistral
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gemma llama3
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gpt4 llama3
python3 run_cheat_task.py ../reproductions/Autosave-China-60 gpt4 mistral