cd ../tasks
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gpt4 china gpt4
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gemma china gemma
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome llama3 china llama3
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome mistral china mistral
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gpt3.5 china gpt3.5
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gpt4 china mistral
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gemma china mistral
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome llama3 china mistral
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gpt4 china gemma
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gpt4 china llama3
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gemma china llama3
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gemma china gpt4
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome llama3 china gpt4
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome llama3 china gemma
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome mistral china gpt4
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome mistral china gemma
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome mistral china llama3
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gpt3.5 china gpt4
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gpt3.5 china gemma
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gpt3.5 china llama3
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gpt3.5 china mistral
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gpt4 china gpt3.5
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gemma china gpt3.5
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome llama3 china gpt3.5
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome mistral china gpt3.5
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gpt4 china mistral
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gpt3.5 china gpt4
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome llama3 china gpt4
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gpt4 china gpt3.5
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome gemma china gpt3.5
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome llama3 china gpt3.5
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome mistral china gpt3.5
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome mistral china gpt4
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome mistral china gemma
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome mistral china llama3
python3 run_bargain_task.py ../reproductions/Autosave-China-60 rome llama3 china gemma

